### ISSUE TITLE
Error or nothing wrong

### ISSUE THREAD

**Issue by kellixon** [Vazkii/Patchouli#134]
[10:02:59] [Client thread/TRACE] [FML]: Sending event FMLLoadCompleteEvent to mod patchouli
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 3 column 5 path $.name
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.gson.Gson.fromJson(Gson.java:902)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.gson.Gson.fromJson(Gson.java:825)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.book.BookContents.loadEntry(BookContents.java:203)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.book.BookContents.lambda$reload$1(BookContents.java:140)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.util.ArrayList.forEach(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:140)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:204)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.util.HashMap$Values.forEach(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.common.book.BookRegistry.reload(BookRegistry.java:87)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.base.ClientProxy.loadComplete(ClientProxy.java:32)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.common.base.Patchouli.loadComplete(Patchouli.java:47)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[10:02:59] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:02:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 3 column 5 path $.name
[10:02:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[10:02:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[10:02:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[10:02:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214)
[10:02:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at com.google.gson.Gson.fromJson(Gson.java:887)
[10:02:59] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 50 more
[10:02:59] [Client thread/TRACE] [FML]: Sent event FMLLoadCompleteEvent to mod patchouli
[10:02:59] [Client thread/DEBUG] [FML]: Bar Step: LoadComplete - Patchouli took 0.052s

**Comment by williewillus** [comment]
there's a malformed json in the book somewhere
