### ISSUE TITLE
It crashes when i open a modded world 1.12.2 

### ISSUE THREAD

**Issue by Izhtare** [Vazkii/Patchouli#255]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Xaeros_Minimap_20.12.2_Forge_1.12.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 6/16/20 10:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mystical Lib (mysticallib)
Caused by: java.lang.NoSuchMethodError: epicsquid.mysticallib.LibRegistry.addSlabPair(Lnet/minecraft/block/material/Material;Lnet/minecraft/block/SoundType;FLjava/lang/String;Lnet/minecraft/block/state/IBlockState;[Lnet/minecraft/block/Block;ZLnet/minecraft/creativetab/CreativeTabs;)V
	at epicsquid.roots.init.ModBlocks.variants(ModBlocks.java:173)
	at epicsquid.roots.init.ModBlocks.registerBlocks(ModBlocks.java:114)
	at epicsquid.roots.RegistryManager.init(RegistryManager.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_151_RegistryManager_init_RegisterContentEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at epicsquid.mysticallib.LibRegistry.initAll(LibRegistry.java:74)
	at epicsquid.mysticallib.proxy.CommonProxy.preInit(CommonProxy.java:17)
	at epicsquid.mysticallib.proxy.ClientProxy.preInit(ClientProxy.java:25)
	at epicsquid.mysticallib.MysticalLib.preInit(MysticalLib.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 148647320 bytes (141 MB) / 349646848 bytes (333 MB) up to 2431909888 bytes (2319 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx2332M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version          | Source                                | Signature                                |
	|:----- |:-------------------------- |:---------------- |:------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                  | 1.12.2           | minecraft.jar                         | None                                     |
	| LCH   | mcp                        | 9.42             | minecraft.jar                         | None                                     |
	| LCH   | FML                        | 8.0.99.99        | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                      | 14.23.5.2854     | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | xaerominimap_core          | 1.12.2-1.0       | minecraft.jar                         | None                                     |
	| LCH   | guideapi                   | 1.12-2.1.8-63    | Guide-API-1.12-2.1.8-63.jar           | None                                     |
	| LCH   | bloodmagic                 | 1.12.2-2.4.3-105 | BloodMagic-1.12.2-2.4.3-105.jar       | None                                     |
	| LCH   | bookshelf                  | 2.3.590          | Bookshelf-1.12.2-2.3.590.jar          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | improvedbackpacks          | 1.12.2-1.5.0.0   | ImprovedBackpacks-1.12.2-1.5.0.0.jar  | None                                     |
	| LCH   | jei                        | 4.15.0.293       | jei_1.12.2-4.15.0.293.jar             | None                                     |
	| LCH   | mantle                     | 1.12-1.3.3.55    | Mantle-1.12-1.3.3.55.jar              | None                                     |
	| LCH   | roots                      | 1.12.2-3.0.25    | Roots-1.12.2-3.0.25.jar               | None                                     |
	| LCH   | mysticalworld              | 1.12.2-1.7.1     | mysticalworld-1.12.2-1.7.1.jar        | None                                     |
	| LCH   | patchouli                  | 1.0-20           | Patchouli-1.0-20.jar                  | None                                     |
	| LCH   | ruins                      | 17.1             | Ruins-1.12.2.jar                      | None                                     |
	| LCH   | tlauncher_custom_cape_skin | 1.4              | tlskincape_1.12.2-1.4.jar             | None                                     |
	| LCH   | xaerominimap               | 20.12.2          | Xaeros_Minimap_20.12.2_Forge_1.12.jar | None                                     |
	| LCE   | mysticallib                | 1.12.2-1.7.0     | mysticallib-1.12.2-1.7.0.jar          | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Xaeros_Minimap_20.12.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27017' Renderer: 'AMD 15D8:C9'

**Comment by williewillus** [comment]
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mystical Lib (mysticallib)

not patchouli
