### ISSUE TITLE
book crash 1.12.2

### ISSUE THREAD

**Issue by Warbringer12** [Vazkii/Patchouli#292]
[latest.log](https://github.com/Vazkii/Patchouli/files/5087669/latest.log)
[crash-2020-08-17_18.28.19-client.txt](https://github.com/Vazkii/Patchouli/files/5087670/crash-2020-08-17_18.28.19-client.txt)

experienced this while in game
crashed straight to desktop

**Comment by Hubry** [comment]
The TFC book is broken here.
```
		Book loading error: java.lang.RuntimeException: Error while loading entry tfc:reference/quern
			at vazkii.patchouli.client.book.BookContents.lambda$reload$3(BookContents.java:149)
-snip-
		Caused by: java.lang.RuntimeException: Error while loading entry tfc:reference/quern page 2
			at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:182)
			at vazkii.patchouli.client.book.BookContents.lambda$reload$3(BookContents.java:147)
			... 47 more
		Caused by: java.lang.NullPointerException: Unknown Quern recipe: tfc:borax
			at java.util.Objects.requireNonNull(Objects.java:228)
			at net.dries007.tfc.compat.patchouli.QuernComponent.build(QuernComponent.java:31)
			at vazkii.patchouli.client.book.template.component.ComponentCustom.build(ComponentCustom.java:25)
```
