### ISSUE TITLE
1.16.3 crash lastest version when logging onto servers 

### ISSUE THREAD

**Issue by FullMetalMaster** [Vazkii/Patchouli#321]
-- Head --
Thread: Render thread
Stacktrace:
	at vazkii.patchouli.client.handler.BookRightClickHandler.getHoveredEntry(BookRightClickHandler.java:117) ~[?:1.16.2-47] {re:classloading}
	at vazkii.patchouli.client.handler.BookRightClickHandler.onRenderHUD(BookRightClickHandler.java:48) ~[?:1.16.2-47] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_189_BookRightClickHandler_onRenderHUD_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:832) ~[?:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:222) ~[?:?] {re:classloading}
-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['Keiserk'/49167, l='ClientLevel', x=14.99, y=80.00, z=12.01], RemoteClientPlayerEntity['FeiryJaquar'/49051, l='ClientLevel', x=81.70, y=67.00, z=-29.63]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (9,78,6), Chunk: (at 9,4,6 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1426441 game time, 1460991 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server

seems to only happen with some players idk if it has to do with the in game gui not being set or something

**Comment by williewillus** [comment]
update patchouli and forge fully
