### ISSUE TITLE
[1.16.3] Mixin injection error on loading a world

### ISSUE THREAD

**Issue by Theking5301** [Vazkii/Patchouli#327]
Here's an interesting one...might be related forge version mismatches? I removed my mod's patchouli_books folder and still had the same issue. Could also be related to some poor code on my end?

**Minecraft Version:** 1.16.3
**Patchouli Version:** 1.16.2-47 & 1.16.2-48-SNAPSHOT
**Mappings:** 20200916-1.16.2
**Forge Version:** 1.16.3-34.1.0
```

[Netty Local Client IO #0/FATAL] [mixin/]: Mixin apply failed assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager -> net.minecraft.client.multiplayer.ClientAdvancementManager: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on patchouli_onSync could not find any targets matching 'Lnet/minecraft/client/multiplayer/ClientAdvancementManager;func_192799_a(Lnet/minecraft/network/play/server/SAdvancementInfoPacket;)V' in net.minecraft.client.multiplayer.ClientAdvancementManager. Using refmap patchouli.refmap.json [PREINJECT Applicator Phase -> assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager -> Prepare Injections ->  -> handler$zza000$patchouli_onSync(Lnet/minecraft/network/play/server/SAdvancementInfoPacket;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on patchouli_onSync could not find any targets matching 'Lnet/minecraft/client/multiplayer/ClientAdvancementManager;func_192799_a(Lnet/minecraft/network/play/server/SAdvancementInfoPacket;)V' in net.minecraft.client.multiplayer.ClientAdvancementManager. Using refmap patchouli.refmap.json [PREINJECT Applicator Phase -> assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager -> Prepare Injections ->  -> handler$zza000$patchouli_onSync(Lnet/minecraft/network/play/server/SAdvancementInfoPacket;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_222] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_222] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_222] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_222] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) [mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) [mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) [mixin-0.8.1.jar:0.8.1+unknown-b0.git-unknown] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) [modlauncher-7.0.1.jar:7.0.1+78+master.e9771d8] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:256) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:135) [modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:97) [modlauncher-7.0.1.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_222] {}
	at net.minecraft.client.network.play.ClientPlayNetHandler.<init>(ClientPlayNetHandler.java:360) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.network.login.ClientLoginNetHandler.handleLoginSuccess(ClientLoginNetHandler.java:103) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.login.server.SLoginSuccessPacket.processPacket(SLoginSuccessPacket.java:53) [?:?] {re:classloading}
	at net.minecraft.network.login.server.SLoginSuccessPacket.processPacket(SLoginSuccessPacket.java:13) [?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.processPacket(NetworkManager.java:157) [?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147) [?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:50) [?:?] {re:classloading}
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:304) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:446) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:51) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:404) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}
```

**Comment by Theking5301** [comment]
Egg on my face - failed to see the issue that had already been closed for this (I made the mistake of only looking for 1.16.3). Solution for anyone who comes across this: https://github.com/Vazkii/Patchouli#mixin-troubleshooting.
