### ISSUE TITLE
1.16.4 Forge Patchouli into Eclipse IDE fails injection on world load

### ISSUE THREAD

**Issue by Wabbit0101** [Vazkii/Patchouli#339]
OS: Windows 7
Environment: Eclipse IDE (Java 8 pretty old!)
Minecraft: 1.16.4
Forge: 35 -> 1.16.4-35.1.12
MCP mappings: 20201028-1.16.3
Patchouli: 1.16.4-48  (forge)
Build instruction: `runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:1.16.4-48")`

I get the error below on world load (the game starts up ok, but world load fails). I have checked the mcp mappings and `read` is `func_192799_a` as mod seems to want. 

I'm assuming I'm doing something wrong or missing a dependency but can't see what it would be? (note this used to work up to 1.15.2 but I believe it used a coremod and now uses the mixin)

```
[17:17:18] [Netty Local Client IO #0/DEBUG] [mixin/]: Mixing client.MixinClientAdvancementManager from assets/patchouli/patchouli.mixins.json into net.minecraft.client.multiplayer.ClientAdvancementManager
[17:17:18] [Netty Local Client IO #0/FATAL] [mixin/]: Mixin apply failed assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager -> net.minecraft.client.multiplayer.ClientAdvancementManager: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on patchouli_onSync could not find any targets matching 'Lnet/minecraft/client/multiplayer/ClientAdvancementManager;func_192799_a(Lnet/minecraft/network/play/server/SAdvancementInfoPacket;)V' in net.minecraft.client.multiplayer.ClientAdvancementManager. Using refmap patchouli.refmap.json [PREINJECT Applicator Phase -> assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager -> Prepare Injections ->  -> handler$zza000$patchouli_onSync(Lnet/minecraft/network/play/server/SAdvancementInfoPacket;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on patchouli_onSync could not find any targets matching 'Lnet/minecraft/client/multiplayer/ClientAdvancementManager;func_192799_a(Lnet/minecraft/network/play/server/SAdvancementInfoPacket;)V' in net.minecraft.client.multiplayer.ClientAdvancementManager. Using refmap patchouli.refmap.json [PREINJECT Applicator Phase -> assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager -> Prepare Injections ->  -> handler$zza000$patchouli_onSync(Lnet/minecraft/network/play/server/SAdvancementInfoPacket;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_112] {}
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_112] {}
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_112] {}
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_112] {}
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown] {}
    at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) [modlauncher-8.0.6.jar:8.0.6+85+master.325de55] {}
    at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) [modlauncher-8.0.6.jar:?] {}
    at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) [modlauncher-8.0.6.jar:?] {}
    at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.0.6.jar:?] {}
    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) [modlauncher-8.0.6.jar:?] {re:classloading}
    at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-8.0.6.jar:?] {re:classloading}
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_112] {}
    at net.minecraft.client.network.play.ClientPlayNetHandler.<init>(ClientPlayNetHandler.java:360) [?:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.client.network.login.ClientLoginNetHandler.handleLoginSuccess(ClientLoginNetHandler.java:119) [?:?] {re:classloading,pl:runtimedistcleaner:A}
    at net.minecraft.network.login.server.SLoginSuccessPacket.processPacket(SLoginSuccessPacket.java:53) [?:?] {re:classloading}
    at net.minecraft.network.login.server.SLoginSuccessPacket.processPacket(SLoginSuccessPacket.java:13) [?:?] {re:classloading}
    at net.minecraft.network.NetworkManager.processPacket(NetworkManager.java:156) [?:?] {re:classloading}
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:146) [?:?] {re:classloading}
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49) [?:?] {re:classloading}
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:304) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:446) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:51) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:404) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final] {}
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112] {}
```

**Comment by williewillus** [comment]
3557

**Comment by Wabbit0101** [comment]
<sigh>... I really must try to remember "the scrollbar thing" on the project landing page might be useful. Thank you that solved the problem!
