### ISSUE TITLE
Book not reverting to default language when a world is loaded in another locale than english

### ISSUE THREAD

**Issue by toktoktheeo** [Vazkii/Patchouli#346]
Hi,

The team of Nature's Aura redirected me here. You can see the original issue here: https://github.com/Ellpeck/NaturesAura/issues/174.

I'm on: Minecraft 1.164, Forge 35.1.28, Patchouli 48.

When I load or create a world in an other language than english, some pages from the guide book are missing.
Instead of reverting to the default language (english) they are blank.

And the log tell me this:

> [19:18:56] [Render thread/ERROR] [patchouli/]: Error while loading contents for book naturesaura:book
java.lang.RuntimeException: Error building entry naturesaura:using/animal_spawner
at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:141) ~[patchouli:1.16.4-48] {re:classloading}
at java.util.HashMap$Values.forEach(Unknown Source) ~[?:1.8.0_202] {}
at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:137) ~[patchouli:1.16.4-48] {re:classloading}
at vazkii.patchouli.common.book.Book.reloadContents(Book.java:186) ~[patchouli:1.16.4-48] {re:classloading}
at java.util.HashMap$Values.forEach(Unknown Source) ~[?:1.8.0_202] {}
at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:104) ~[patchouli:1.16.4-48] {re:classloading}
at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[patchouli:1.16.4-48] {re:classloading}
at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:40) ~[patchouli:1.16.4-48] {re:classloading,re:mixin}
at net.minecraft.client.multiplayer.ClientAdvancementManager.handler$zbn000$patchouli_onSync(SourceFile:518) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager,pl:mixin:A}
at net.minecraft.client.multiplayer.ClientAdvancementManager.func_192799_a(SourceFile:57) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager,pl:mixin:A}
at net.minecraft.client.network.play.ClientPlayNetHandler.func_191981_a(ClientPlayNetHandler.java:1275) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:37) ~[?:?] {re:classloading,re:mixin}
at net.minecraft.network.play.server.SAdvancementInfoPacket.func_148833_a(SourceFile:16) ~[?:?] {re:classloading,re:mixin}
at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?] {re:classloading,xf:OptiFine:default}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.4-client.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202] {}
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.28-launcher.jar:35.1] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}
at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_202] {}
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_202] {}
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
Caused by: java.lang.RuntimeException: Error while loading entry naturesaura:using/animal_spawner page 28
at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:224) ~[patchouli:1.16.4-48] {re:classloading}
at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[patchouli:1.16.4-48] {re:classloading}
... 39 more
Caused by: java.lang.RuntimeException: Unknown entity id:
at vazkii.patchouli.common.util.EntityUtil.loadEntity(EntityUtil.java:44) ~[patchouli:1.16.4-48] {re:classloading}
at vazkii.patchouli.client.book.template.component.ComponentEntity.build(ComponentEntity.java:39) ~[patchouli:1.16.4-48] {re:classloading}
at vazkii.patchouli.client.book.template.BookTemplate.lambda$build$0(BookTemplate.java:121) ~[patchouli:1.16.4-48] {re:classloading}
at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_202] {re:computing_frames}
at vazkii.patchouli.client.book.template.BookTemplate.build(BookTemplate.java:120) ~[patchouli:1.16.4-48] {re:classloading}
at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:24) ~[patchouli:1.16.4-48] {re:classloading}
at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:221) ~[patchouli:1.16.4-48] {re:classloading}
at vazkii.patchouli.client.book.BookContents.lambda$reload$5(BookContents.java:139) ~[patchouli:1.16.4-48] {re:classloading}
... 39 more

![2021-01-01_19 34 07](https://user-images.githubusercontent.com/34038708/103454505-31b37b80-4ce5-11eb-92b0-b71d5fba690b.png)

If I load the world in english and then switch the language (to french in this case) the issue is not present.

I have optifine installed but I tried an instance with only Nature's Aura, Patchouli and Jei (without optifine) and the issue is still present.

Have a nice day.

**Comment by kappa-maintainer** [comment]
This problem still exists.
