### ISSUE TITLE
I started to get this error, not able to join the game

### ISSUE THREAD

**Issue by SaraXianLin** [Vazkii/Patchouli#351]
![imagen](https://user-images.githubusercontent.com/77309538/104838881-4108fc00-5883-11eb-891e-b06c4686fe37.png)

Debug log
https://gist.github.com/SaraXianLin/1ae53d369979659c0e4a426f39265ddd

**Comment by Hubry** [comment]
```
[17ene2021 05:11:29.630] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid patchouli
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: evolved_rpg:Evolved RPG  guide
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?]
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:42) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.lambda$null$1(BookRegistry.java:66) ~[patchouli:1.16.4-48]
```
All characters in the book location must match the regex `[a-z0-9/._-]`, the Evolved RPG book's location is `Evolved RPG  guide`, which contains spaces and uppercase characters. Not a Patchouli issue.
