### ISSUE TITLE
issue while loading with curseforge app

### ISSUE THREAD

**Issue by muggicookies** [Vazkii/Patchouli#395]
here's the log and btw. i don't know what happened i also tried to switch versions but it still crashed

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
  LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 5/6/21 4:16 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Patchouli (patchouli)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at vazkii.patchouli.client.base.ClientAdvancements.<clinit>(ClientAdvancements.java:34)
	at vazkii.patchouli.common.book.BookRegistry.reload(BookRegistry.java:89)
	at vazkii.patchouli.client.base.ClientProxy.loadComplete(ClientProxy.java:35)
	at vazkii.patchouli.common.base.Patchouli.loadComplete(Patchouli.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 787053464 bytes (750 MB) / 2080374784 bytes (1984 MB) up to 12884901888 bytes (12288 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2766 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                 | Version              | Source                                      | Signature                                |
	|:------- |:------------------ |:-------------------- |:------------------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft          | 1.12.2               | minecraft.jar                               | None                                     |
	| UCHIJA  | mcp                | 9.42                 | minecraft.jar                               | None                                     |
	| UCHIJA  | FML                | 8.0.99.99            | forge-1.12.2-14.23.4.2766.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge              | 14.23.4.2766         | forge-1.12.2-14.23.4.2766.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | foamfixcore        | 7.7.4                | minecraft.jar                               | None                                     |
	| UCHIJA  | opencomputers|core | 1.7.5.192            | minecraft.jar                               | None                                     |
	| UCHIJA  | aiimprovements     | 0.0.1.3              | AIImprovements-1.12-0.0.1b3.jar             | None                                     |
	| UCHIJA  | bettercombatmod    | 1.5.6                | BetterCombat-1.12.2-1.5.6.jar               | None                                     |
	| UCHIJA  | betterquesting     | 3.5.329              | BetterQuesting-3.5.329.jar                  | None                                     |
	| UCHIJA  | bookshelf          | 2.3.590              | Bookshelf-1.12.2-2.3.590.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA  | camera             | 1.0.10               | camera-1.0.10.jar                           | None                                     |
	| UCHIJA  | clumps             | 3.1.2                | Clumps-3.1.2.jar                            | None                                     |
	| UCHIJA  | reskillable        | 1.12.2-1.13.0        | Reskillable-1.12.2-1.13.0.jar               | None                                     |
	| UCHIJA  | compatskills       | 1.12.2-1.17.0        | CompatSkills-1.12.2-1.17.0.jar              | None                                     |
	| UCHIJA  | customnpcs         | 1.12                 | CustomNPCs_1.12.2-(05Jul20).jar             | None                                     |
	| UCHIJA  | enchdesc           | 1.1.20               | EnchantmentDescriptions-1.12.2-1.1.20.jar   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA  | foamfix            | 0.10.11-1.12.2       | foamfix-0.10.11-1.12.2.jar                  | None                                     |
	| UCHIJA  | gravestone         | 1.10.3               | gravestone-1.10.3.jar                       | None                                     |
	| UCHIJA  | inventorysorter    | 1.13.3+57            | inventorysorter-1.12.2-1.13.3+57.jar        | None                                     |
	| UCHIJA  | inventorytweaks    | 1.64+dev.151.822d839 | InventoryTweaks-1.64+dev.151.jar            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA  | ironchest          | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar             | None                                     |
	| UCHIJA  | landmanager        | 1.5.0                | landmanager-1.12.2-1.5.0.jar                | None                                     |
	| UCHIJA  | lostcities         | 2.0.22               | lostcities-1.12-2.0.22.jar                  | None                                     |
	| UCHIJA  | minetraps          | 1.0.4                | MineTraps-1.12.2-(v.1.0.4).jar              | None                                     |
	| UCHIJA  | mmdlib             | 1.0.0-rc2            | MMDLib-1.12-1.0.0-rc2.36.jar                | None                                     |
	| UCHIJA  | modernmetals       | 2.5.0-rc2            | ModernMetals-1.12-2.5.0-rc2.152.jar         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA  | modnametooltip     | 1.10.1               | modnametooltip_1.12.2-1.10.1.jar            | None                                     |
	| UCHIJA  | mousetweaks        | 2.10                 | MouseTweaks-2.10-mc1.12.2.jar               | None                                     |
	| UCHIJA  | mw                 | 0.4.4.6              | mw_2.0-0.4.4.6_mc1.12.2.jar                 | None                                     |
	| UCHIJA  | bq_npc_integration | 3.4.34               | NPCIntegration-3.4.34.jar                   | None                                     |
	| UCHIJA  | opencomputers      | 1.7.5.192            | OpenComputers-MC1.12.2-1.7.5.192.jar        | None                                     |
	| UCHIJA  | orespawn           | 3.3.1                | OreSpawn-1.12-3.3.1.179.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJEE | patchouli          | 1.0-22               | Patchouli-1.0-22.jar                        | None                                     |
	| UCHIJ   | pizzacraft         | 2.0.19               | PizzaCraft-1.12.2-2.0.19.jar                | None                                     |
	| UCHIJ   | scp                | 2.4.0                | SCP_Lockdown-1.12.2-2.4.0-hotfix.jar        | None                                     |
	| UCHIJ   | spartanshields     | 1.5.4                | SpartanShields-1.12.2-1.5.4.jar             | None                                     |
	| UCHIJ   | spartanweaponry    | beta 1.3.8           | SpartanWeaponry-1.12.2-beta-1.3.8.jar       | None                                     |
	| UCHIJ   | bq_standard        | 3.4.173              | StandardExpansion-3.4.173.jar               | None                                     |
	| UCHIJ   | toughnessbar       | @VERSION@            | toughnessbar-2.4.jar                        | None                                     |
	| UCHIJ   | phosphor-lighting  | 1.12.2-0.2.7         | phosphor-forge-mc1.12.2-0.2.7-universal.jar | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  
weaponlib (mw_2.0-0.4.4.6_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
LoadingPlugin (Reskillable-1.12.2-1.13.0.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.11-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.51' Renderer: 'GeForce RTX 2060/PCIe/SSE2'
	Patchouli open book context: n/a

**Comment by Hubry** [comment]
Update Forge, you are using a horribly old build.

**Comment by muggicookies** [comment]
But to what version? I’m using 1.12.2 because of my server which also runs
on 1.12.2 so what curseforge version should I update to that’s inside of
1.12.2?

tor. 6. maj 2021 kl. 16.43 skrev Hubry ***@***.***>:

**Comment by muggicookies** [comment]
Sorry I couldn’t see the version you also mentioned in the mail and somehow
it didn’t show up until I got into GitHub

Btw. I will try that version and see if it helps

tor. 6. maj 2021 kl. 17.56 skrev ThatAnonymousGuy ***@***.***>:
