### ISSUE TITLE
Crash upon marking book as read.

### ISSUE THREAD

**Issue by Reshy** [Vazkii/Patchouli#398]
```
[15:09:27] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.crash.ReportedException: mouseClicked event handler
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:434) ~[?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?]
	at net.minecraft.client.MouseHelper$$Lambda$21911/394961968.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:106) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?]
	at net.minecraft.client.MouseHelper$$Lambda$18359/980370756.invoke(Unknown Source) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?]
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:398) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.0.42.jar:36.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$476/1422262786.call(Unknown Source) [forge-1.16.5-36.0.42.jar:36.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
Caused by: java.lang.StackOverflowError
	at net.minecraft.util.text.StringTextComponent.equals(SourceFile:34) ~[?:?]
	at vazkii.patchouli.client.book.gui.button.GuiButtonBookMarkRead.markCategoryAsRead(GuiButtonBookMarkRead.java:50) ~[?:1.16.4-51]
	at vazkii.patchouli.client.book.gui.button.GuiButtonBookMarkRead.markCategoryAsRead(GuiButtonBookMarkRead.java:53) ~[?:1.16.4-51]
	at vazkii.patchouli.client.book.gui.button.GuiButtonBookMarkRead.markCategoryAsRead(GuiButtonBookMarkRead.java:53) ~[?:1.16.4-51]
---- snip of ~1000 lines of the same method recursing -Hubry ----
	at vazkii.patchouli.client.book.gui.button.GuiButtonBookMarkRead.markCategoryAsRead(GuiButtonBookMarkRead.java:53) ~[?:1.16.4-51]
	at vazkii.patchouli.client.book.gui.button.GuiButtonBookMarkRead.markCategoryAsRead(GuiButtonBookMarkRead.java:53) ~[?:1.16.4-51]
[15:09:27] [Render thread/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 5/8/21 3:09 PM
Description: mouseClicked event handler

java.lang.StackOverflowError: mouseClicked event handler
	at net.minecraft.util.text.StringTextComponent.equals(SourceFile:34) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
```

**Comment by Hubry** [comment]
@Reshy If you could, please post full the crash report file, ideally using something like [GitHub Gist](https://gist.github.com/). And you can delete all the repeating lines of the stacktrace in there, I edited your post because scrolling past all of them really sucks on mobile.

**Comment by NillerMedDild** [comment]
Possibly better crash report: https://paste.ee/p/wPRum
