### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by benbenlaw** [Vazkii/Patchouli#426]
so i use excompressum in my modpack, when i get a advancement i get a freeze and this shows in the log 

java.lang.IllegalArgumentException: Extension Book excompressum:lexicon has no valid target
    at vazkii.patchouli.common.book.Book.reloadExtensionContents(Book.java:198) ~[patchouli:1.16.4-53.1]
    at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0_242]
    at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:106) ~[patchouli:1.16.4-53.1]
    at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[patchouli:1.16.4-53.1]
    at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:40) ~[patchouli:1.16.4-53.1]

 this is because the book its trying to add to is botania which is not in my modpack

**Comment by williewillus** [comment]
that's a problem with that mod, not Patchouli.

**Comment by williewillus** [comment]
hang fixed by 14fcf637febf19224b3eaa7485f27f203fa80ad1. As for the underlying issue, soft-dep extensions aren't really a thing in Patchouli. This will be solved long term with resource pack books in 1.17-1.18.

**Comment by CuboidDroid** [comment]
Just want to say thanks for sorting this one
👍
